#!/system/bin/sh
# Color管理器 WebUI 安装脚本
ui_print "=============================="
ui_print "   Color管理器 WebUI 模块"
ui_print "=============================="
ui_print ""
ui_print " 功能: 网页版调度参数/调速器/电芯管理"
ui_print " 纯本地运行无需联网, 局域网设备无法访问"
ui_print " 端口: 8765 (仅本机, http://127.0.0.1:8765)"
ui_print ""
ui_print " 前置条件: Termux 中安装 python"
ui_print "   pkg install python"
ui_print ""
ui_print " 安装后重启一次即自动启动服务"
ui_print " 无 python 时每30秒重试直到安装成功"
ui_print ""
ui_print " 手动启动/停止(不重启):"
ui_print "   su -c 'sh /data/adb/modules/color_webui/service.sh'"
ui_print "   su -c 'pkill -f server.py'"
ui_print "=============================="
