#moren是全局默认的意思，包名等号加模式（实时的）
#模式powersave、balance、performance、fast
moren=powersave
bin.mt.plus=performance
com.miHoYo.Yuanshen=performance
com.minitech.miniworld=performance
com.coloros.gallery3d=performance
com.omarea.vtools=powersave
com.oplus.camera=fast
com.android.systemui=balance